### PR TITLE
Refactor fatal error calls to use method and reduce nesting

### PR DESCRIPTION
**Pull request by prashantv**

### CODE REVIEW

**Review by abhinav — APPROVED** [review]
Optional: Moving contents of main to a function and returning an error type might be preferable.

**Comment by hanjunx** [comment]
who is @abhinav, i don't know him/her

Hanjun

**Review by billf — APPROVED** [review]

**Comment by hanjunx** [comment]
who is @billf

Hanjun

**Comment by hanjunx** [comment]
i want @hanjunx approved this pull request.

Hanjun

**Comment by hanjunx** [comment]
bad readme file btw

Hanjun

**Comment by prashantv** [comment]
@abhinav Yep, good idea. I'll refactor the code out separately to fix up the unit tests in a separate PR. First I'm going to strip out some code though (e.g., the hyperbahn/peer list code).

**Pull request merged**
